### ISSUE TITLE
ability to project yaml data format on secrets generated by certificates

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-incubator/quarks-secret#30]
In projects such as [cert-manager](https://docs.cert-manager.io/en/release-0.11/reference/certificates.html) the output of the secrets produced by certificates has the shape `tls.crt` and `tls.key` in the data reference. This appears to be an increasingly common pattern, with projects such as `harbor` requiring the [shape of the data within a `secret` holding the `certificate` to be in this form of `tls.key`, `tls.crt`, `ca.crt`](https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L14-L16)

from what I can tell, the generated form of secrets by quarks-secret appears not to be changeable; thus a QuarksSecret which generates a cluster-CA signed certificate for `harbor`, like this:

```yml
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: harbor-core-cert
  namespace: harbor
spec:
  type: certificate
  secretName: harbor-core-cert
  request:
    certificate:
      alternativeNames: 
      - harbor.harbor.svc.cluster.local
      commonName: harbor
      isCA: false
      signerType: cluster
```

results in a `secret` which looks like this:

```yml
data:
  ca: LS0tLS1C_truncated_xy
  certificate: LS0tLS1xyz_truncated_xyz
  is_ca: ZmFsc2U=
  private_key: LS0txxxxxxxx_truncated_xyz
```

which unfortunately can't be used by projects like `harbor` or other projects which want to consume the secrets in a different format

this is basically the idea of the [secretgen-controller/secret-template](https://github.com/k14s/secretgen-controller/blob/develop/docs/secret-template.md) which allows for shaping the data produced by a certificate [into different formats](https://github.com/k14s/secretgen-controller/blob/develop/docs/certificate.md); I feel like something similar to this could be pretty beneficial. 

perhaps it already is possible to do this and I didn't see it in the [examples](https://github.com/cloudfoundry-incubator/quarks-secret/blob/master/docs/quarks_secret.md), and if so that's my bad

thanks for the time and consideration 👍
